In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [30]:
from sklearn.cross_validation import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.utils import shuffle

In [31]:
data=pd.read_csv("IRIS (2).csv")   #importing the data file
data.head()   #a glimpse of the database

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [32]:
data.columns=['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']
data=shuffle(data,random_state=False)
data.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width          Species
114           5.8          2.8           5.1          2.4   Iris-virginica
62            6.0          2.2           4.0          1.0  Iris-versicolor
33            5.5          4.2           1.4          0.2      Iris-setosa
107           7.3          2.9           6.3          1.8   Iris-virginica
7             5.0          3.4           1.5          0.2      Iris-setosa

In [33]:
real_x=data.iloc[:,:4].values
real_y=data.iloc[:,4].values
le=LabelEncoder()
real_y=le.fit_transform((real_y).astype('str'))  #making the categorical variable to numerical
real_y

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1,
       1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0,
       0, 2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2,
       1, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0], dtype=int64)

In [34]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=0.25,random_state=0) #splitting model

In [35]:
classifier=LogisticRegression(random_state=False)
classifier.fit(train_x,train_y)
classifier.predict(test_x)

array([2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 0, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1,
       2, 1, 2, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 2, 0, 2], dtype=int64)

In [36]:
cm=confusion_matrix(test_y,classifier.predict(test_x))
cm

array([[11,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 16]], dtype=int64)

In [37]:
print(accuracy_score(test_y,classifier.predict(test_x))*100)

97.36842105263158
